apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # Get storage that can be used by a single node at a time with read/write access
    - ReadWriteOnce
  resources:
    requests:
      # Get 2GB of space
      storage: 2Gi
