name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Run tests on dev container
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test
      # Build images
      - run: docker build -t k02d/multi-client ./client
      - run: docker build -t k02d/multi-nginx ./nginx
      - run: docker build -t k02d/multi-server ./server
      - run: docker build -t k02d/multi-worker ./worker
      # Push images to docker hub
      - run: docker push k02d/multi-client
      - run: docker push k02d/multi-nginx
      - run: docker push k02d/multi-server
      - run: docker push k02d/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Copy Beanstalk Deploy action from https://github.com/marketplace/actions/beanstalk-deploy
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          # this bucket is in the S3 section on AWS
          existing_bucket_name: elasticbeanstalk-us-east-2-704683640657
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
